development:
  cloud_name: dacsanvietnam
  api_key: '877886197526953'
  api_secret: yY-0sXnUO14Ex9PY0HwODs5J6G4
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dacsanvietnam
  api_key: '877886197526953'
  api_secret: yY-0sXnUO14Ex9PY0HwODs5J6G4
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dacsanvietnam
  api_key: '877886197526953'
  api_secret: yY-0sXnUO14Ex9PY0HwODs5J6G4
  enhance_image_tag: true
  static_file_support: false