development:
  stripe_publishable_key: 'pk_test_51KvAmZEivTknVUA30PrAQrp7EwCbx01LVr3vl3C2oZsOwZbiGYH9QwRC79Tz0CbtpeO7klrAgLQ4oRqa4wbHkLYt00GTFWqair'
  stripe_secret_key: 'sk_test_51KvAmZEivTknVUA3QcOLXFjo06PgZG5p7zfrUjI15xiLBWfsAnjCxIyPsHqSCM04sZ98gW3V1PxYZFMQ6jjVI0F300jmjIUWUN'
production:
  stripe_publishable_key: 'pk_test_51KvAmZEivTknVUA30PrAQrp7EwCbx01LVr3vl3C2oZsOwZbiGYH9QwRC79Tz0CbtpeO7klrAgLQ4oRqa4wbHkLYt00GTFWqair'
  stripe_secret_key: 'sk_test_51KvAmZEivTknVUA3QcOLXFjo06PgZG5p7zfrUjI15xiLBWfsAnjCxIyPsHqSCM04sZ98gW3V1PxYZFMQ6jjVI0F300jmjIUWUN'